# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TGi38QXUpGhK2b6uBPpS43Ih3HgqcdFz
"""
import mysql.connector
from mysql.connector import Error

def create_server_connection():
    connection = None
    try:
        connection = mysql.connector.connect(user='root', 
        password='12345678', host='localhost', port='3306', database='user_db'
        )
        print("MySQL Database connection successful")
    except Error as err:
        print(f"Error: '{err}'")

    return connection

create_server_connection()